name: Build Docker image
on:
  push:
    branches:
    - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: download aws cli
      run: |
          pwd
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          ls
    
    - name: build docker image
      run: |
        docker build -t mytfe:1.0 .
